// <auto-generated />
using System;
using BandApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BandApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BandApi.Models.album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BandId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("character varying(400)")
                        .HasMaxLength(400);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("BandId");

                    b.ToTable("albums");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7547c210-fcc8-11ea-adc1-0242ac120002"),
                            BandId = new Guid("f2e4cffc-fcc7-11ea-adc1-0242ac120002"),
                            Description = "one of the best bands ever",
                            Title = "master of puppets"
                        },
                        new
                        {
                            Id = new Guid("7547c45e-fcc8-11ea-adc1-0242ac120002"),
                            BandId = new Guid("f2e4cffc-fcc7-11ea-adc1-0242ac120002"),
                            Description = "amazing rock albumn with raw sound",
                            Title = "appetite for destrcution"
                        },
                        new
                        {
                            Id = new Guid("7547c558-fcc8-11ea-adc1-0242ac120002"),
                            BandId = new Guid("f2e4cffc-fcc7-11ea-adc1-0242ac120002"),
                            Description = "very gloomy albumn",
                            Title = "waterloo"
                        });
                });

            modelBuilder.Entity("BandApi.Models.band", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Founded")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MainGenre")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("bands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2e4cffc-fcc7-11ea-adc1-0242ac120002"),
                            Founded = new DateTime(1988, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "HeavyMetal",
                            Name = "Metallica"
                        },
                        new
                        {
                            Id = new Guid("f2e4d240-fcc7-11ea-adc1-0242ac120002"),
                            Founded = new DateTime(1985, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Rock",
                            Name = "Guns N Roses"
                        },
                        new
                        {
                            Id = new Guid("f2e4d344-fcc7-11ea-adc1-0242ac120002"),
                            Founded = new DateTime(1965, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Disco",
                            Name = "ABBA"
                        },
                        new
                        {
                            Id = new Guid("f2e4d416-fcc7-11ea-adc1-0242ac120002"),
                            Founded = new DateTime(1985, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Alternative",
                            Name = "Oasis"
                        },
                        new
                        {
                            Id = new Guid("f2e4d4de-fcc7-11ea-adc1-0242ac120002"),
                            Founded = new DateTime(1981, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Pop",
                            Name = "A-ha"
                        });
                });

            modelBuilder.Entity("BandApi.Models.album", b =>
                {
                    b.HasOne("BandApi.Models.band", "band")
                        .WithMany("albumns")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
